 name: Deploy


   on:
     push:
       branches:
         - main


  jobs:
    test:
      runs-out: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12
            with:
              heroku_api_key: ${{secrets.HEROKU_API_KEY}}
              heroku_api_name: "unserprojekt"
              heroku_email: "asahm.98@gmail.com"
              - name: clean build
                run: ./gradlew clean test --info --stacktrace


